### ISSUE TITLE
Cannot implement custom History: `ReedlineError` is private

### ISSUE THREAD

**Issue by ClementNerma** [nushell/reedline#545]
Currently you can't implement your own `History` type as multiple trait functions return a `Result<_, ReedlineError>`, but `ReedlineError` (which comes from the private `result` module) is not available to use outside of the crate.

Would it be possible to make it available publicly?

Thanks!

**Comment by sholderbach** [comment]
Yes I think there is nothing speaking against that in my view. The trait should be implementation agnostic/tolerant. 

While we are at it, it might make sense to make it either more general or replace it with a more specific name, as most of reedline just returns `std::io::error`s for the fallible interactions with the terminal. (Most of the reedline errors at the moment don't seem to  actionable for the library users)

**Comment by ClementNerma** [comment]
I just opened a PR for this at #661

**Comment by sholderbach** [comment]
Looking at the current state of the history system, I think we still have some serious gremlins lurking there.

See the unfinished error handling around how we deal with the different capabilities of `SqliteHistory` and `FileBackedHistory` (`.expect("TODO: error handling")` doesn't sound like a long term solution). Also assumptions around how big the history minimally is seem to pop up as https://github.com/nushell/nushell/issues/10826. We have some work to do here to make things more robust and easier to understand.

So I don't want to give any stability promises with regards to the API of the `History` trait and related parts.

I don't want to discourage you from experimenting with implementing your own `History` and reporting what pops up.
But keep in mind that we may be a moving target or prioritize robustness over total flexibility in the future (as some of the issues we see right now may be due to premature flexibility)

**Comment by ClementNerma** [comment]
I'm actually building a shell on top of `reedline`. But it's a personal project that isn't designed for public use before it's entirely finished and heavily tested, so even if there are major API breakages it's not a problem for me :)
