### ISSUE TITLE
After `ExecuteHostCommand` is handled, new prompt is rendered

### ISSUE THREAD

**Issue by kit494way** [nushell/reedline#755]
**Platform** Windows 11 WSL2 Ubuntu 20.04,
**Terminal software** wsltty 3.5.1

Describe the problem you are observing.

## Steps to reproduce

```nu
❯ def do_nothing [] {}
❯ let x = {name: do_nothing, modifier: control, keycode: char_g, mode: [vi_normal, vi_insert], event: {send: executehostcommand, cmd: 'do_nothing'}}
❯ $env.config.keybindings = ($env.config.keybindings | append $x)
❯ # type C-g here, then new prompt is rendered
❯
```

**Comment by fdncred** [comment]
I had to add `emacs` to `mode:` but yes, it does draw a new prompt. 

I wonder if that's because it's just like "hitting enter" somehow? I haven't looked into it in a while so I don't remember. I have quite a few keybindings that use executehostcommand. It would be good to not render a new prompt if we don't have to.
